export const images = {
  Home: require('../assets/images/home.png'),
  Search: require('../assets/images/search.png'),
  Leaderboard: require('../assets/images/leaderboard.png'),
  Trophy: require('../assets/images/trophy.png'),
  Leaderboard: require('../assets/images/leaderboard.png'),
  User: require('../assets/images/user.png'),
  Comment: require('../assets/images/comment.png'),
  Logo: require('../assets/images/logo.png'),
  Edit: require('../assets/images/edit.png'),
  Logout: require('../assets/images/logout.png'),
  MoonStar: require('../assets/images/moonStar.png'),
  DownErrow: require('../assets/images/downErrow.png'),
  UpperErrow: require('../assets/images/upperErrow.png'),
  menducky: require('../assets/images/menducky.png'),
  profile: require('../assets/images/profileImage.png'),

  Group: require('../assets/images/group.png'),
  Clock: require('../assets/images/clock.png'),
  Background: require('../assets/images/background.png'),
  Rupee: require('../assets/images/rupee.png'),
  Vector2: require('../assets/images/vector2.png'),
  Fill: require('../assets/images/fill.png'),
  Fill2: require('../assets/images/fill2.png'),
};
