export const strings = {
  Profile: 'Profile',
  Jina_Simons: 'Jina Simons',
  Pts_600: '6000 Pts',
  bio: 'I’m a software developer that has been in the crypto space since 2012. And I’ve seen it grow and falter over a period of time. Really happy to be here!',
  LOGOUT: 'LOGOUT',
  Under_or_Over: 'Under or Over',
  Number81: '81%',
  Top_5: 'Top 5',
  Number51: '-51%',
  Games_played: 'Games played',
  Badges: 'Badges',

  YourPrediction: 'Your Prediction is Under',
  ENTRY_TICKETS: 'ENTRY TICKETS',
  You_can_win: 'You can win ',
  $2000: '$2000',
  Total: 'Total',
  Number5: '5',
  Submit_my_prediction: 'Submit my prediction',

  Todays_Games: 'Today’s Games',
  UNDER_OR_OVER: 'UNDER OR OVER',
  Starting_in: 'Starting in',
  Bitcoin_Price: 'Bitcoin Price will be under',
  Time: '03:23:12',
  $24: '$24,524 at 7 a ET on 22nd Jan’21',
  PRIZE_POOL: 'PRIZE POOL',
  $12: '$12,000',
  UNDER: 'UNDER',
  Number325x: '3.25x',
  OVER: 'OVER',
  ENTRY_FEES: 'ENTRY FEES',
  Whats_your: 'What’s your prediction?',
  Players355: '355 Players',
  View_chart: 'View chart',
  predicted_under232: '232 predicted under',
  predicted_over123: '123 predicted over',
  Number125x: '1.25x',
};
